import { type GameState, isGameState } from "./gameSchema";

export function validateGameState(raw: unknown): GameState {
  if (!isGameState(raw)) {
    console.error("❌ Invalid AI output:", raw);
    throw new Error("Invalid game state generated by AI");
  }

  return {
    ...raw,
    difficulty: raw.difficulty ?? "easy",
  };
}
