import { GameSchema, GameState } from "./gameSchema";

export function validateGameState(raw: unknown): GameState {
  const parsed = GameSchema.safeParse(raw);

  if (!parsed.success) {
    console.error("❌ Invalid AI output:", parsed.error.format());
    throw new Error("Invalid game state generated by AI");
  }

  return parsed.data;
}
