import { CONTROL_SCHEMES, ENTITY_KINDS, RULE_TYPES, SHAPES } from "@/engine/capabilities";

export const SUPPORTED_ENTITY_TYPES = ENTITY_KINDS;
export const SUPPORTED_SHAPES = SHAPES;
export const SUPPORTED_CONTROLS = CONTROL_SCHEMES;
export const SUPPORTED_RULES = RULE_TYPES;

export const ENGINE_CAPABILITIES = {
  entityTypes: SUPPORTED_ENTITY_TYPES,
  shapes: SUPPORTED_SHAPES,
  controls: SUPPORTED_CONTROLS,
  rules: SUPPORTED_RULES,
} as const;
